### ISSUE TITLE
Uncaught TypeError: AtomCodealikePlugin.startTracking is not a function

### ISSUE THREAD

**Issue by royhenengel** [Codealike/Codealike-Atom#13]
[Enter steps to reproduce:]

1. ... Removed folder from the project pane
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [codealike](https://github.com/codealike/codealike-atom) package 0.0.8

### Stack Trace

Uncaught TypeError: AtomCodealikePlugin.startTracking is not a function

```
At C:\Users\henen\.atom\packages\codealike\lib\codealike-atom.js:107

TypeError: AtomCodealikePlugin.startTracking is not a function
    at /packages/codealike/lib/codealike-atom.js:107:27
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Project.module.exports.Project.removePath (~/AppData/Local/atom/app-1.21.1/resources/app/src/project.js:372:28)
    at TreeView.module.exports.TreeView.removeProjectFolder (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/tree-view/lib/tree-view.js:1271:35)
    at HTMLDivElement.atom.commands.add.tree-view:remove-project-folder (~/AppData/Local/atom/app-1.21.1/resources/app/node_modules/tree-view/lib/tree-view.js:385:32)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:381:36)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.21.1/resources/app/src/command-registry.js:266:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.21.1/resources/app/src/atom-environment.js:1354:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.21.1/resources/app/src/application-delegate.js:348:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:34.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:15.4.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-beautify 0.30.6 
atom-formatter-jsbeautify 1.1.2 
atom-material-numix-syntax 0.2.1 
atom-material-syntax 1.0.7 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.6 
atom-panda-syntax 0.18.0 
chester-atom-syntax 0.3.0 
codealike 0.0.8 
dracula-syntax 2.0.5 
dracula-ui 0.6.0 
file-icons 2.1.13 
language-log 1.9.0 
minimap 4.29.7 
pretty-json 1.6.4 
wakatime 7.0.3 
```

**Comment by soke1556** [comment]
@henengel thanks for reporting this. I'm not able to reproduce it. I've also tried to remove the folder from project pane while keeping the focus on a file contained in the folder. Can you please include an screenshot of the error you see? Nevertheless we're going to keep trying to reproduce it. Thanks again!

**Comment by joelgarciajr84** [comment]
![captura de tela de 2018-01-23 11 00 03](https://user-images.githubusercontent.com/969999/35277098-b0721700-002c-11e8-9a11-0155b71be32b.png)

Same Here
